### ISSUE TITLE
"sudo npm start" Opens to black screen.

### ISSUE THREAD

**Issue by ghost** [philipptrenz/photo-booth#44]
When I run the PhotoBooth program with "sudo npm start" a black window opens and nothing happens. When I click the screen with my mouse or press my button connected to pin 3 nothing happens and the camera appears to also be doing nothing. I enabled gpio in the config file so it should be working. Any suggestions? Thanks!

**Comment by philipptrenz** [comment]
Please enable `init.showDevTools` inside the `config.json` and report the output of the javascript console.

**Comment by philipptrenz** [comment]
Any progress here?

**Comment by ZuluForce** [comment]
First off, thanks for writing and maintaining this software!

I'm using Ubuntu 16.04 to test and I experienced the same black screen. This is the error from the dev tools:
```
Uncaught Error: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /[path]/photo_booth/node_modules/sharp/build/Release/../../vendor/lib/libpng16.so.16)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/[path]/photo_booth/node_modules/sharp/lib/constructor.js:10:15)
    at Object.<anonymous> (/[path]/photo_booth/node_modules/sharp/lib/constructor.js:259:3)
```

I found this issue thread on the sharp project that discusses this exact issue: https://github.com/lovell/sharp/issues/892

I initially tried installing a newer version of zlib on my system but that didn't fix anything. I then found success exporting the `LD_PRELOAD` env variable with `export LD_PRELOAD=node_modules/sharp/vendor/lib/libz.so`. I then ran `npm start` in the same shell.

I'm not a javascript developer so I'm not sure if this is silly but I added a `require('sharp')` to the top of the main.js before `require('electron')` because some people suggested an earlier library load was finding the system installed zlib 1.2.8 instead of the statically linked one shipped with sharp. This did not solve the issue but it did fail fast with an error at the command line instead of creating a black window.

So, I'm not sure what this project should do. Perhaps people just need to update to a later version of Ubuntu where the default installed zlib is newer.

**Comment by philipptrenz** [comment]
Hi @ZuluForce, thanks for sharing your experience!
It's not the first time a zlib version conflict gets reported (see #23 and #29) and I'm aware of the conflict between sharp and electron. zlib v1.2.8 as well as the v1-branch of Electron which is still currently used for photo-booth has several vulnerabilities. I consider photo-booth to be no security sensitive application, but nevertheless my aim is to upgrade dependencies to unaffected versions. This should also fix the conflicting versions of zlib.
I tried to upgrade dependencies some months ago with the result, that newer versions of Electron won't run on the Raspberry Pi. 
As Electron started semantic versioning beginning with v2.0 and as there are stable releases of it available now I'll risk a new start in the foreseeable future.

**Comment by philipptrenz** [comment]
Closing due to inactivity

**Comment by mlenkeit** [comment]
For anybody else coming across this issue: I ran into the same problem and specifying `LB_PRELOAD` helped me, too. I didn't try to upgrade the dependencies though.

I ended up changing the `start` script in the `package.json` to include `LB_PRELOAD`:
```json
"start": "LD_PRELOAD=node_modules/sharp/vendor/lib/libz.so electron"
```

**Comment by philipptrenz** [comment]
@mlenkeit Thanks!
